@url = https://localhost:7109

POST {{url}}/api/auth/register
Content-Type: application/json

{
    "firstName": "Bishorup",
    "lastName": "Banjara",
    "email": "email@innerdinner.com",
    "password": "Password1!"
}